apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab9
spec:
  selector:
    matchLabels:
      run: server
  replicas: 2
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
        - name: lab5
          image: localhost:32000/lab5:registry
          ports:
            - containerPort: 50051
              protocol: TCP
